version: '3.8'
 
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.10
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
    ports:
      - "9092:9092"
      - "9644:9644"

  postgres:
     image: postgres:15
     container_name: postgres
     environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: healthcare
     ports:
       - "5432:5432"